pipeline {
    //agent { docker { image 'node:16.17.1-alpine' } }
      triggers {
        pollSCM 'H/2 * * * *'
           }
    options {
        disableConcurrentBuilds()
    }
    agent any
    stages {
        stage('build') {
            when {
                branch 'main'
            }
            steps {
                 dir('back-end/python/embedding-api') {                     
                sh '''
                API=$(cat ../../../../../env)
                sed -i s/OPENAI_API_KEY_HERE/$API/g Dockerfile
                '''
                //sh "cat .env"
                sh 'docker stop backend2 || true'
                sh 'docker rm backend2 || true'
                sh 'docker rmi hp/node-web-app2 || true'
                sh 'docker build -t hp/node-web-app2 .'
                sh 'docker run --name backend2 -p 8082:80 -d hp/node-web-app2'
                 }
            }
        }
    }
}
