pipeline {
    //agent { docker { image 'node:16.17.1-alpine' } }
      triggers {
        pollSCM 'H/2 * * * *'
           }
    options {
        disableConcurrentBuilds()
    }
    agent any
    stages {
        stage('build') {
            when {
                branch 'main'
            }
            steps {
                 dir('front-end') {                     
                sh 'docker stop frontend || true'
                sh 'docker rm frontend || true'
                sh 'docker rmi hp/node-web-server || true'
                sh 'docker build -t hp/node-web-server .'
                sh 'docker run --name frontend -p 80:80 -d hp/node-web-app'
                 }
            }
        }
    }
}
