pipeline {
    //agent { docker { image 'node:16.17.1-alpine' } }
      triggers {
        pollSCM 'H/2 * * * *'
           }
    options {
        disableConcurrentBuilds()
    }
    agent any
    stages {
        stage('build') {
            when {
                branch 'main'
            }
            steps {
                 dir('back-end') {                     
                sh '''
                API=$(cat ../../../env)
                sed -i s/OPENAI_API_KEY_HERE/$API/g .env
                '''
                sh "cat .env"
                sh 'docker stop backend || true'
                sh 'docker rm backend || true'
                sh 'docker rmi hp/node-web-app || true'
                sh 'docker build -t hp/node-web-app .'
                sh 'docker run --name backend -p 8081:3100 -d hp/node-web-app'
                 }
            }
        }
    }
}
